### ISSUE TITLE
Is it possible to turn off automatic tooltips for selection?

### ISSUE THREAD

**Issue by gerardnico** [ComboStrap/combo#93]
### Discussed in https://github.com/ComboStrap/combo/discussions/92

<div type='discussions-op-text'>

<sup>Originally posted by **vaniwiki** April  7, 2024</sup>
I like automatic tooltips, showing relevant information across my website. But they should not be everywhere. For example, I have a long list of links that do not need any link tooltips, but just remain as links. Is there any way to turn this feature off for certain parts, like a box or card with some syntax like `<box tooltip="none">` or similar...?</div>

**Comment by gerardnico** [comment]
The [preview attribute in a link](https://combostrap.com/content/the-link-component-x0oocdu2#preview) does not take into account the value false.

**Comment by gerardnico** [comment]
This link should not return any tooltip
```
[[?preview=false|preview of the actual page]]
```

**Comment by gerardnico** [comment]
It comes from this [line](https://github.com/ComboStrap/combo/blob/main/ComboStrap/LinkMarkup.php#L257) where the code set true if the attribute is present and does not check the value at all.

**Comment by vaniwiki** [comment]
This would be very helpful combined with iterator, so I can turn off redundant descriptions where I already show them in its fragment... Previosuly my autotooltip plugin showed me only tooltips from certain places, only in certain places, so I could control more easily where tooltips would display... (They had a namespace list with regex for include or exclude. I think that shold come as standard with every plugin, actually.)

**Comment by gerardnico** [comment]
Done

**Comment by vaniwiki** [comment]
Here is another aspect of the same issue:

The `?preview=false` argument may not show the preview, but it still shows full description on hover as the browser tooltip.

Is there a way to make it show only the page-id, like how DokuWiki usually works, when `?preview=false` flag is given?
